### ISSUE TITLE
文档 1.9.5 基础知识-连接 章节有错别字

### ISSUE THREAD

**Issue by NewNameArk** [wildfirechat/docs#2]
https://docs.wildfirechat.cn/base_knowledge/connect.html  
文档 1.9.5 基础知识-连接 章节有错别字
0.0.3. 连接状态  连接状态  ConnectionStatusServerDown 对应的处理方法列中 “需要检查服务器是否当机”   中的 “当” 应该改为 “宕”

**Comment by heavyrain2012** [comment]
已经修改，感谢
